### ISSUE TITLE
[Bug] Rate limit后，再次翻译会从头重新开始

### ISSUE THREAD

**Issue by hadwinn** [gnehs/subtitle-translator-electron#1]
#### Rate limit后，再次翻译会从头重新开始，已经翻译过的部分又会再次翻译。
![image](https://user-images.githubusercontent.com/73227570/224461365-db902354-ae90-40fb-ad51-e68787a4e0ee.png)

**Comment by gnehs** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/16719720/224474108-7bc0cf23-1a0a-4d1d-b199-bd603d675089.png">
已在 API 欄位中新增提示

We have added a tooltip in the API field.
