### ISSUE TITLE
经常提示“api额度已用馨”

### ISSUE THREAD

**Issue by kinson08** [gnehs/subtitle-translator-electron#102]
我使用了3-5个api来加速翻译，速度确实是提高了，但是在翻译到70-80%左右的时候经常出现“您的api额度已用馨”的提示，而且无法保留进度，只能重新再尝试几次，大概试了3-4次至少会成功一次。考虑是否是rate limitation，我已经把延迟设置在25了。

**Comment by gnehs** [comment]
你是使用免費試用的帳號嗎？

**Comment by kinson08** [comment]
是的，免费试用的账户应该限速是3次/分钟。

**Comment by Tim-Feng** [comment]
我用了付費 API 也是在今天開始遇到這個問題，但 OPENAI 的 API usage 還離 cap 相當遠

**Comment by Zack5891** [comment]
我有付費訂閱GPT，但我也遇到相同的問題

**Comment by kinson08** [comment]
解决的方法是降低请求速率，甚至网络速度，还是可以使用的。不过还有一个问题，就是在翻译疑问句的时候，chatgpt经常自作聪明用自己的方式再回答问题，而不是翻译字幕，给出来的答案是英文的，只能手工进行修改。

**Comment by MrFutureV** [comment]
> 解决的方法是降低请求速率，甚至网络速度，还是可以使用的。不过还有一个问题，就是在翻译疑问句的时候，chatgpt经常自作聪明用自己的方式再回答问题，而不是翻译字幕，给出来的答案是英文的，只能手工进行修改。

所以就是提高delay吗
