### ISSUE TITLE
[Help] the title of help wanted report 我填写了OpenAI api key ，但还是提升我要输入密匙。

### ISSUE THREAD

**Issue by peaceful610** [gnehs/subtitle-translator-electron#103]
#### Describe the problem you confuse
![微信截图_20240228025521](https://github.com/gnehs/subtitle-translator-electron/assets/129727914/7c021e9c-bbde-4d11-8bc3-bb328cedfcb8)
![微信截图_20240228025542](https://github.com/gnehs/subtitle-translator-electron/assets/129727914/5cee8bec-5fdf-4d0e-9109-7e6fd6858dc4)

**Comment by gnehs** [comment]
可能是你輸入的 api key 有誤或失效導致的
