### ISSUE TITLE
[Help]Is it possible to enhance compatibility with KoboldCPP or LM Studio API？

### ISSUE THREAD

**Issue by lin16303** [gnehs/subtitle-translator-electron#104]
as the translation functionality is visible in the backend but the software seems to be unable to provide feedback. the translation is completed within the software, there won't be any displayed text.thanks
![2024-03-06 (2)](https://github.com/gnehs/subtitle-translator-electron/assets/130566478/d4e3eba1-d420-4c94-af90-5387116ab224)
![2024-03-06](https://github.com/gnehs/subtitle-translator-electron/assets/130566478/787d1aa4-b8ec-43ef-95fd-84faff3bcf95)

**Comment by gnehs** [comment]
Based on testing, the translation quality of local execution is not very good, and it also cannot stably output in JSON format. Therefore, local models are currently not supported.
