### ISSUE TITLE
[Help] 提示无法翻译该行字幕

### ISSUE THREAD

**Issue by saturndec** [gnehs/subtitle-translator-electron#105]
已经设置好了API和URL，但是还是提示无法翻译该行字幕，都翻译不了，这是什么情况呀

**Comment by szshineshi** [comment]
同样的问题，win11下，运行Subtitle Translate软件，设置好OPEN的KEY和URL，翻译英文字母到中文，提示无法翻译该行字幕，是什么原因？如何处理？
<img width="600" alt="微信图片_20240312170854" src="https://github.com/gnehs/subtitle-translator-electron/assets/146796917/f7d228d2-d488-48dd-9ba8-996d08a48b90">

**Comment by saturndec** [comment]
我这边解决了，是API有问题，我换了一个API就可以了
