### ISSUE TITLE
设置好OPEN的KEY和URL，翻译英文字母到中文，提示无法翻译该行字幕

### ISSUE THREAD

**Issue by szshineshi** [gnehs/subtitle-translator-electron#106]
#### Describe the problem you confuse
同样的问题，win11下，运行Subtitle Translate软件，设置好OPEN的KEY和URL，翻译英文字母到中文，提示无法翻译该行字幕，是什么原因？如何处理？
<img width="600" alt="微信图片_20240312170854" src="https://github.com/gnehs/subtitle-translator-electron/assets/146796917/d8587564-b1bd-487a-b5bc-1c82d963028a">

**Comment by szshineshi** [comment]
<img width="620" alt="微信图片_20240312172419" src="https://github.com/gnehs/subtitle-translator-electron/assets/146796917/e3994635-25ce-4495-a8f9-4ecd0bd0bb65">
这个怎么搞？哪里配置gpt-3.5-turbo的参数？

**Comment by szshineshi** [comment]
抱歉，找到原因了，原来是KEY的后台没有勾选gpt-3.5-0613选项，现在可以了，谢谢！

**Comment by Evil2Elf** [comment]
怎么勾选

**Comment by Ponderfly** [comment]
希望能支持自定义模型,有些代理站不支持0613 这个模型
