### ISSUE TITLE
Support version users can choose models

### ISSUE THREAD

**Issue by tvone** [gnehs/subtitle-translator-electron#109]
Here is my customized version, while waiting for this repository to update
https://github.com/tvone/subtitle-translator-electron/releases/tag/1.3.2

**Comment by aierlma** [comment]
Love you tvone! This customized ver is fantastic!

**Comment by aierlma** [comment]
I'm not quite clear on whether the custom model sends the context version or the non-context version? (Sorry I'm not very familiar with electron and js)

**Comment by gnehs** [comment]
<img width="801" alt="image" src="https://github.com/gnehs/subtitle-translator-electron/assets/16719720/9460970d-fc7a-4a55-8b20-a5b793c2b4b1">
Version 1.4.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/latest
