### ISSUE TITLE
[Bug] The new version cannot correctly calculate the cost.

### ISSUE THREAD

**Issue by aierlma** [gnehs/subtitle-translator-electron#110]
#### Which method you use?

- [x] `gpt-4-turbo`
- [ ] `gpt-3.5-turbo`
- [ ] `gpt-3.5-turbo-economy`

It seems that in the new version 1.4.0 the gpt-4-turbo model cannot correctly calculate the cost. The correct cost should be 1 dollar, but it shows as 0.06, suspecting that it was calculated based on the default gpt-3.5-turbo price.

**Comment by A18on** [comment]
I have the same problem.

**Comment by gnehs** [comment]
We are currently fixing this issue and expect to release a new version this week.

**Comment by gnehs** [comment]
Fixed in version 1.5.0
