### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by haihua-tv** [gnehs/subtitle-translator-electron#112]
#### Which method you use?

gpt-4

#### Provide your subtitle file
[2311221.zip](https://github.com/gnehs/subtitle-translator-electron/files/15083075/2311221.zip)

#### Target language

English

#### Additional notes

Failed to translate line:诸位好 

#### Describe the bug
我是ChatGPT的会员，无法正常翻译。
无论是3.5还是4 都无法正常翻译，
不存在翻墙问题。

**Comment by gnehs** [comment]
API and ChatGPT memberships are billed separately. Please ensure that you have added your credit card at https://platform.openai.com/settings/organization/billing/overviews.

**Comment by Aeslyy** [comment]
I have the same problem.



![image](https://github.com/gnehs/subtitle-translator-electron/assets/121048781/1ce753e9-947e-40df-9c25-2673e3523e81)

**Comment by Aeslyy** [comment]
> API and ChatGPT memberships are billed separately. Please ensure that you have added your credit card at https://platform.openai.com/settings/organization/billing/overviews.

I tested the API in Subtitle Edit and here (https://cerlancism.github.io/chatgpt-subtitle-translator/) and it works, but when I put it in the program it doesn't work.
I will release a test API: _**sk-proj-ALM0yYpqhOcoBOWhxVdZT3BlbkFJFfrMm3eAIN3uiA4vziDu**_
