### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by LYS2424** [gnehs/subtitle-translator-electron#119]
#### Describe the problem you confuse
Author, the software is definitely a very good subtitle translation software, but I encountered two problems when using it and I don't know how to solve them. Help me and I'll treat you to coffee

<html>
<body>
<ol class="tree-outline hide-selection-when-blurred issues" role="tree" tabindex="-1" jslog="Tree" style="box-sizing: border-box; min-width: 0px; min-height: 0px; padding: 0px; margin: 0px; z-index: 0; position: relative; overflow: auto; --issue-indent: 8px; list-style-type: none; color: rgb(31, 31, 31); font-family: &quot;Segoe UI&quot;, tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="issue parent expanded" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; padding-top: 0px; padding-right: 8px; padding-bottom: 0px; padding-left: var(--issue-indent); overflow: hidden; flex: 0 0 auto; transition: background-color 200ms ease 0s; border-top-color: ; border-top-style: ; border-right-color: ; border-right-style: ; border-bottom-color: ; border-bottom-style: ; border-left-color: ; border-left-style: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-width: 0px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat: ; background-attachment: ; background-origin: ; background-clip: ; background-color: var(--sys-color-state-hover-on-subtle);"><div class="header" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row; align-items: flex-start; padding: 4px 0px; cursor: pointer; width: 2115.08px;"><div class="title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 0%; font-size: 12px; color: var(--sys-color-on-surface); font-weight: 450; user-select: text; padding-top: 2px;">Reading cookie in cross-site context will be blocked in future Chrome versions</div><devtools-hide-issues-menu style="box-sizing: border-box; min-width: 0px; min-height: 0px; visibility: visible;"><button class="hide-issues-menu-btn" title="Hide issues" style="position: relative; display: flex; background-color: transparent; flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; margin: 0px -2px 0px 4px; overflow: hidden; border-radius: 0px; border: none;"><devtools-icon name="dots-vertical" role="presentation" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 20px; height: 20px; color: var(--icon-default); vertical-align: sub; position: relative;"><span style="display: block; width: 20px; height: 20px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-dots-vertical);"></span></devtools-icon></button></devtools-hide-issues-menu></div></li><ol class="children body issue-kind-breaking-change expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding-left: calc(var(--issue-indent) + 43px); border-bottom: 1px solid var(--sys-color-divider); padding-top: 6px; position: relative; padding-bottom: 26px; padding-right: 8px; display: block;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent" aria-posinset="1" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><devtools-markdown-view style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="message" style="line-height: 20px; font-size: 14px; color: var(--override-markdown-view-message-color,--sys-color-token-subtle); margin-bottom: 4px; user-select: text;"><p style="margin-bottom: 16px; margin-block-start: 2px;">Cookies with the<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">SameSite=None; Secure</code><span> </span>and not<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">Partitioned</code><span> </span>attributes that operate in cross-site contexts are third-party cookies. In future Chrome versions, reading third-party cookies will be blocked. This behavior protects user data from cross-site tracking.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">Please refer to the article linked to learn more about preparing your site to avoid potential breakage.</p></div></devtools-markdown-view></li><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent parent expanded affected-resources-label" aria-expanded="true" aria-posinset="2" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; margin-top: 5px; font-size: 10px; font-weight: 500; letter-spacing: 0.06em; text-transform: uppercase; color: var(--sys-color-on-surface); display: flex; text-overflow: ellipsis; white-space: normal; position: relative; align-items: flex-start;">AFFECTED RESOURCES</li><ol class="children expanded affected-resources" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 3px 0px 0px; position: relative; user-select: text; display: block;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="parent expanded" aria-expanded="true" aria-posinset="1" aria-setsize="1" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start; margin-top: 0px; padding: 2px 5px 0px; background: var(--sys-color-cdt-base-container);"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><div class="affected-resource-label" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-size: 12px; line-height: 18px; color: var(--sys-color-on-surface); position: relative; cursor: pointer;">2 cookies</div></li><ol class="children expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 6px 0px 9px 5px; display: block; background: var(--sys-color-cdt-base-container); margin-bottom: 10px;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span>
Name | Domain & Path
-- | --
__cf_bm | .api.openai.com/
_cfuvid | .api.openai.com/

</li></ol></ol><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent link-wrapper selected" aria-posinset="3" aria-setsize="3" tabindex="0" aria-selected="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; outline-width: 0px; margin-top: 15px; user-select: text; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><ul class="link-list" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; list-style-position: inside; padding-inline-start: 0px;"><li style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><x-link class="link devtools-link" tabindex="0" role="link" target="_blank" rel="noopener" href="https://goo.gle/3pcd-dev-issue" title="https://goo.gle/3pcd-dev-issue" jslog="Link; track: click; context: learn-more" style="box-sizing: border-box; min-width: 0px; min-height: 0px; cursor: pointer; text-decoration: underline; color: var(--sys-color-primary); outline-offset: 2px; font-size: 12px; padding-top: 4px; display: inline;"><devtools-icon role="presentation" name="open-externally" class="link-icon" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--icon-link); vertical-align: sub; position: relative; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-right: 0.5ch;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-open-externally);"></span></devtools-icon>Learn more: Prepare for phasing out third-party cookies</x-link></li></ul></li></ol></ol>
</body>
</html>

<html>
<body>
<ol class="tree-outline hide-selection-when-blurred issues" role="tree" tabindex="-1" jslog="Tree" style="box-sizing: border-box; min-width: 0px; min-height: 0px; padding: 0px; margin: 0px; z-index: 0; position: relative; overflow: auto; --issue-indent: 8px; list-style-type: none; color: rgb(31, 31, 31); font-family: &quot;Segoe UI&quot;, tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="issue parent expanded" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; padding-top: 0px; padding-right: 8px; padding-bottom: 0px; padding-left: var(--issue-indent); overflow: hidden; flex: 0 0 auto; transition: background-color 200ms ease 0s; border-top-color: ; border-top-style: ; border-right-color: ; border-right-style: ; border-bottom-color: ; border-bottom-style: ; border-left-color: ; border-left-style: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-width: 0px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat: ; background-attachment: ; background-origin: ; background-clip: ; background-color: var(--sys-color-state-hover-on-subtle);"><div class="header" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row; align-items: flex-start; padding: 4px 0px; cursor: pointer; width: 2115.08px;"><div class="title" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 0%; font-size: 12px; color: var(--sys-color-on-surface); font-weight: 450; user-select: text; padding-top: 2px;">Setting cookie in cross-site context will be blocked in future Chrome versions</div><devtools-hide-issues-menu style="box-sizing: border-box; min-width: 0px; min-height: 0px; visibility: visible;"><button class="hide-issues-menu-btn" title="Hide issues" style="position: relative; display: flex; background-color: transparent; flex: 0 0 auto; align-items: center; justify-content: center; padding: 0px; margin: 0px -2px 0px 4px; overflow: hidden; border-radius: 0px; border: none;"><devtools-icon name="dots-vertical" role="presentation" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 20px; height: 20px; color: var(--icon-default); vertical-align: sub; position: relative;"><span style="display: block; width: 20px; height: 20px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-dots-vertical);"></span></devtools-icon></button></devtools-hide-issues-menu></div></li><ol class="children body issue-kind-breaking-change expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding-left: calc(var(--issue-indent) + 43px); border-bottom: 1px solid var(--sys-color-divider); padding-top: 6px; position: relative; padding-bottom: 26px; padding-right: 8px; display: block;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent" aria-posinset="1" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><devtools-markdown-view style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="message" style="line-height: 20px; font-size: 14px; color: var(--override-markdown-view-message-color,--sys-color-token-subtle); margin-bottom: 4px; user-select: text;"><p style="margin-bottom: 16px; margin-block-start: 2px;">Cookies with the<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">SameSite=None; Secure</code><span> </span>and not<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">Partitioned</code><span> </span>attributes that operate in cross-site contexts are third-party cookies. In future Chrome versions, setting third-party cookies will be blocked. This behavior protects user data from cross-site tracking.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">Please refer to the article linked to learn more about preparing your site to avoid potential breakage.</p></div></devtools-markdown-view></li><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent parent expanded affected-resources-label" aria-expanded="true" aria-posinset="2" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; margin-top: 5px; font-size: 10px; font-weight: 500; letter-spacing: 0.06em; text-transform: uppercase; color: var(--sys-color-on-surface); display: flex; text-overflow: ellipsis; white-space: normal; position: relative; align-items: flex-start;">AFFECTED RESOURCES</li><ol class="children expanded affected-resources" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 3px 0px 0px; position: relative; user-select: text; display: block;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="parent expanded" aria-expanded="true" aria-posinset="1" aria-setsize="1" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start; margin-top: 0px; padding: 2px 5px 0px; background: var(--sys-color-cdt-base-container);"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><div class="affected-resource-label" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-size: 12px; line-height: 18px; color: var(--sys-color-on-surface); position: relative; cursor: pointer;">2 cookies</div></li><ol class="children expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 6px 0px 9px 5px; display: block; background: var(--sys-color-cdt-base-container); margin-bottom: 10px;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span>
Name | Domain & Path
-- | --
_cfuvid | .api.openai.com/
__cf_bm | .api.openai.com/

</li></ol></ol><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent link-wrapper selected" aria-posinset="3" aria-setsize="3" tabindex="0" aria-selected="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; outline-width: 0px; margin-top: 15px; user-select: text; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><ul class="link-list" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; list-style-position: inside; padding-inline-start: 0px;"><li style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><x-link class="link devtools-link" tabindex="0" role="link" target="_blank" rel="noopener" href="https://goo.gle/3pcd-dev-issue" title="https://goo.gle/3pcd-dev-issue" jslog="Link; track: click; context: learn-more" style="box-sizing: border-box; min-width: 0px; min-height: 0px; cursor: pointer; text-decoration: underline; color: var(--sys-color-primary); outline-offset: 2px; font-size: 12px; padding-top: 4px; display: inline;"><devtools-icon role="presentation" name="open-externally" class="link-icon" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--icon-link); vertical-align: sub; position: relative; box-sizing: border-box; min-width: 0px; min-height: 0px; margin-right: 0.5ch;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-open-externally);"></span></devtools-icon>Learn more: Prepare for phasing out third-party cookies</x-link></li></ul></li></ol></ol>
</body>
</html>

![1](https://github.com/user-attachments/assets/41827041-06e3-4571-96c7-fb82a7e501fd)

**Comment by gnehs** [comment]
That's a warning, not an error.

**Comment by LYS2424** [comment]
So what should I do? When I click on the translation software, it doesn't show the translated text or it shows a translation failure message

**Comment by LYS2424** [comment]
那我该怎么做？我点击翻译软件上没有显示翻译好的或者出现了翻译失败的字样

**Comment by gnehs** [comment]
Are you currently in China? If so, you might encounter issues with internet censorship by the GFW

**Comment by LYS2424** [comment]
是的在中国，我开启了vpn，我的gpt请求是发送成功了但返回电脑出了问题，这是什么问题呢

**Comment by LYS2424** [comment]
我是用你的1.4版本能正常翻译了，我试了4台电脑都不行。但是换1.4就正常能用了，应该是你的1.5有bug

**Comment by LYS2424** [comment]
我是用你的1.4版本能正常翻译了，本来我试了4台电脑1.5版本的，都不行。但是换1.4都正常能用了，应该是你的1.5有bug
