### ISSUE TITLE
Multiple language translation at 1 run

### ISSUE THREAD

**Issue by FurkanGozukara** [gnehs/subtitle-translator-electron#12]
I entered like this it is going on but this is the proper way? I want to translate into multiple languages at 1 run. Or any queue system?

Turkish, Spanish

![image](https://user-images.githubusercontent.com/19240467/226841353-87271c9d-3dd0-46e4-bbe9-c8191d744d51.png)

i am hoping it is :/

**Comment by gnehs** [comment]
There is currently no plan for this feature.
