### ISSUE TITLE
[Bug] buggy translation - files uploaded as attachment 

### ISSUE THREAD

**Issue by FurkanGozukara** [gnehs/subtitle-translator-electron#13]
I have translated the english subtitle into french and results are not correct
i mean the order

they are vtt but to upload here i made them txt

for example 

00:13:37.270 --> 00:13:44.460
The fifth one is this is 200 face training
plus 14 epoch style training plus 20 more

translated as below

237
00:13:37,270 --> 00:13:44,460
La cinquième tentative inclut une formation de 200 époques sur le visage,
combinée à une formation sur le style de 14 époques, puis de 20 époques supplémentaires.
L'entraînement d'époques spécifié ici entraîne une déformation du visage et
endommage considérablement le style, comme vous pouvez le voir.

[english.txt](https://github.com/gnehs/subtitle-translator-electron/files/11040027/english.txt)

[french.txt](https://github.com/gnehs/subtitle-translator-electron/files/11040025/french.txt)

![image](https://user-images.githubusercontent.com/19240467/227052800-0b5f1f06-6484-404d-a1ea-d364875f365b.png)

**Comment by gnehs** [comment]
Version 0.4.0 has been released, which allows you to use the Economy option to save on token costs, or use GPT-4 for higher translation quality. If you encounter any issues after using these options, please let me know.
