### ISSUE TITLE
Translation duplication due to wrong sentence break

### ISSUE THREAD

**Issue by AndersenQin** [gnehs/subtitle-translator-electron#14]
I was using Wisper to transcribe the text, which caused a lot of break errors. A large number of repeated phrases appeared after using the translator. (A large number of sentence break errors resulted in the second half of the paragraph repeating the words of the first half)

**Comment by gnehs** [comment]
Version 0.4.0 has been released, which allows you to use the Economy option to save on token costs, or use GPT-4 for higher translation quality. If you encounter any issues after using these options, please let me know.
