### ISSUE TITLE
[Bug]Sometimes the translation will be interrupted and return to Chinese and the re-translate button on the right will disappear.

### ISSUE THREAD

**Issue by LiMinghuaLiGan** [gnehs/subtitle-translator-electron#15]
#### Describe the bug
![屏幕截图 2023-03-25 220109](https://user-images.githubusercontent.com/50763621/227721844-6e184027-8048-48f8-a21e-11118e3c815a.png)
This is a bug I encountered when using the api of openai with free quota, it seems that after I reached the speed limit, I didn't wait for enough cooling time and clicked translate again too fast to cause the bug, the right retranslate button disappeared and the problem of returning to the original text without returning the translation.

**Comment by LiMinghuaLiGan** [comment]
by the way, can this software automaticly control its request speed to avoid react the free trial rate limit?

**Comment by gnehs** [comment]
Please add a credit card to your account to avoid this error.
