### ISSUE TITLE
[Bug] No translation, it just copies the same subs

### ISSUE THREAD

**Issue by nonprogrammodaunpo** [gnehs/subtitle-translator-electron#16]
#### Describe the bug

-- the day before
0.1 Open Subtitle Translator
0.2 choose English as target language
0.3 choose source file
0.4 translate 
-> translation comes out ok
0.5 close Subtitle Translator

-- the day after
1.0  Open Subtitle Translator
1.1 choose source file
1.2 translate
-> instead of translating, it copies the subs

ADDITIONAL NOTES:
A. the first line is often left empty
B. the second line is the copy of the original language, translation starts from the third line

THANKS FOR THE AWESOME WORK!!!!

**Comment by fattie0926** [comment]
I'm running in to the same issue, tried 0.3.1, 0.3.0, 0.2.0, 0.1.0 are all the same.

Apprecaite for the work too!

**Comment by gnehs** [comment]
Version 0.4.0 has been released, which allows you to use the Economy option to save on token costs, or use GPT-4 for higher translation quality. If you encounter any issues after using these options, please let me know.
