### ISSUE TITLE
[Help] Whether to reduce token consumption

### ISSUE THREAD

**Issue by sayou112** [gnehs/subtitle-translator-electron#17]
#### Describe the problem you confuse
When using it, I found that a sentence needs 400tokens, so the subtitle of an episode needs about 10 tokens, which is too much consumption, can you reduce the consumption

**Comment by sayou112** [comment]
I looked at the code and it seemed to be sent in sentences, with this sentence added after each sentence
You are a program responsible for translating subtitles. Your task is to output the specified target language based on the input text. Please do not create the following subtitles on your own. Please do not output any text other than the translation. You will receive the subtitles as array that needs to be translated, as well as the previous translation results and next subtitle. If you need to merge the subtitles with the following line, simply repeat the translation. Please transliterate the person's name into the local language. Target language: ${targetLanguage}\n\n${additionalNotes}
Can you send it by paragraph and arrange the version at last

**Comment by sayou112** [comment]
https://github.com/cgsvv/AISubtitle
I found someone who had done something similar for reference

**Comment by gnehs** [comment]
Version 0.4.0 has been released, which allows you to use the Economy option to save on token costs, or use GPT-4 for higher translation quality. If you encounter any issues after using these options, please let me know.
