### ISSUE TITLE
[Help] A little suggestion

### ISSUE THREAD

**Issue by moshangssh** [gnehs/subtitle-translator-electron#18]
The translation speed is a bit slow. Can it be optimized?

It seems that the token consumption is a bit high now. Can it be reduced?

Thank you.

**Comment by moshangssh** [comment]
If there are too many lines to translate in the subtitles each time, then the subtitles will become very verbose and the context will be too closely connected.

**Comment by gnehs** [comment]
Version 0.4.0 has been released, which allows you to use the Economy option to save on token costs, or use GPT-4 for higher translation quality. If you encounter any issues after using these options, please let me know.
