### ISSUE TITLE
[Bug] When translating, the notes I added will be returned.

### ISSUE THREAD

**Issue by moshangssh** [gnehs/subtitle-translator-electron#19]
#### Describe the bug
![Snipaste_2023-04-01_21-35-32](https://user-images.githubusercontent.com/58763445/229292487-eaf3c577-0c52-49d2-9c06-0f8abee96154.png)
When translating from Japanese to Simplified Chinese, the notes I added will be returned.

**Comment by gnehs** [comment]
That's an issue with GPT-3. For higher quality translations, please use GPT-4.
