### ISSUE TITLE
如何同时保留双语

### ISSUE THREAD

**Issue by xyh2132** [gnehs/subtitle-translator-electron#22]
#### Describe the problem you confuse
如果是英文,会输出中文,否则相反
如果需要中英文双语字幕,如何解决,期望能解决这个问题

**Comment by gnehs** [comment]
<img width="801" alt="SCR-20230402-muzm" src="https://user-images.githubusercontent.com/16719720/229336270-37905e96-e974-4d01-986c-84d4a0c2b224.png">

0.5.0 新增了儲存選項，可以儲存原始字幕與翻譯後字幕

**Comment by xyh2132** [comment]
完美!高效
