### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by jspasp** [gnehs/subtitle-translator-electron#23]
#### Describe the problem you confuse
Hi, Sir

Is it possible to save the translated SRT as bilingual? See attached picture for reference. If we want to make bilingual SRT file, this function is very useful if could provide the save option to save both original language and translated language into one single SRT file. Current, by default, only the translated target language could be saved as SRT and the original language was lost in the new saved SRT file. Thansk.

![image](https://user-images.githubusercontent.com/31765251/229336576-a2ea9c63-93b8-41a3-a912-d4109239570f.png)

**Comment by gnehs** [comment]
Bilingual option for saving has been added in version 0.5.0.
