### ISSUE TITLE
Time interval setting is required

### ISSUE THREAD

**Issue by lhj5426** [gnehs/subtitle-translator-electron#24]
#### Describe the problem you confuse
![image](https://user-images.githubusercontent.com/30548000/229398225-8269f8c4-0c75-4e0e-a22a-0c588980bc53.png)
There is no time interval, running too fast always prompts this

**Comment by gnehs** [comment]
You need to add a payment method to your account to increase your rate limit.

**Comment by lhj5426** [comment]
>


> You need to add a payment method to your account to increase your rate limit.

If you don’t pay, can you set the running time submission interval?
add this option
