### ISSUE TITLE
[Bug] The model: `gpt-4-0314`

### ISSUE THREAD

**Issue by kepuls** [gnehs/subtitle-translator-electron#29]

**Comment by gnehs** [comment]
Have you received an invitation to access the GPT-4-0314 model from OpenAI?

**Comment by kepuls** [comment]
If it is still on an invitation-only basis, that means no I didn't. I thought that through the API it was open to all. As a future release, you can add some hints for the user, which will make him aware of that. Thanks!

**Comment by gnehs** [comment]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/16719720/230617945-831822fb-7650-4b7c-9118-8b8944bfb624.png">
The current version already has.
