### ISSUE TITLE
[Bug] some sentences were not translated

### ISSUE THREAD

**Issue by mizhewei** [gnehs/subtitle-translator-electron#3]
hello, thanks for this wonderful app. 

Bug: I found that some sentences were not translated when I used it, and the API returned the original text. Can you add the function of single sentence retry?
Sometimes the translation result returned by the API contains the translation of the next sentence. I understand that context helps with translation. Some sentences filter out such results while others do not. I hope it can be fixed.

Thanks again.

**Comment by gnehs** [comment]
Retry feature and subtitle editing have been added in version 0.3.0. After updating the application, these features will be available for use.
