### ISSUE TITLE
[Bug] GPT 3.5 TURBO not translating most of the lines. 

### ISSUE THREAD

**Issue by kepuls** [gnehs/subtitle-translator-electron#30]

**Comment by gnehs** [comment]
could you give me the original subtitle file?

**Comment by kepuls** [comment]
Shure, here you go:
[https://www.dropbox.com/s/a7ao8cwvdts31qq/Omicidio%20all%27italiana%20Ita%20AC3%20Sub%20ita.srt?dl=0](url)

**Comment by gnehs** [comment]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/16719720/230619265-01696993-1932-40bc-9b04-c4a29f0ba5fa.png">
it looks like it's working normally 🤔

**Comment by kepuls** [comment]
For me it started repeating in italian from 123 onwards

**Comment by kepuls** [comment]
As I'm reviewing partial translation it seems that it comes and goes in waves – translates, and then copies the original, translates, and copies the original… Strange…

**Comment by gnehs** [comment]
That's a problem with GPT-3. You can try GPT-4 by joining the GPT-4 API waitlist at https://openai.com/waitlist/gpt-4-api.
