### ISSUE TITLE
[Bug] with \N

### ISSUE THREAD

**Issue by luannbr** [gnehs/subtitle-translator-electron#32]
#### Which method you use?

- [ ] `gpt-4-0314`
- [X] `gpt-3.5-turbo`
- [ ] `gpt-3.5-turbo-economy`
#### Provide your subtitle file

[Tousouchuu Great Mission.zip](https://github.com/gnehs/subtitle-translator-electron/files/11207036/Tousouchuu.Great.Mission.zip)

#### Target language
Português Brasileiro

#### Additional notes
I noticed that sometimes after the \N the continuation of the text disappeared or something like \\\\\\\\\\N appeared
#### Describe the bug
![Screenshot_1226](https://user-images.githubusercontent.com/18580842/231348083-a303e1e3-7294-443c-809d-cbfdf9910b02.jpg)

**Comment by gnehs** [comment]
That's a problem with GPT-3. You can try GPT-4 by joining the GPT-4 API waitlist at https://openai.com/waitlist/gpt-4-api.
