### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by buace12137** [gnehs/subtitle-translator-electron#33]
翻译字幕最终结果总会有一些行未被生成中文字幕（只会合并两行英文），不知道是不是结合上下文的代码出了问题，望解决，非常感谢您的工具分享

**Comment by gnehs** [comment]
That's a problem with GPT-3. You can try GPT-4 by joining the GPT-4 API waitlist at https://openai.com/waitlist/gpt-4-api.
