### ISSUE TITLE
[Bug] 下一行的内容会合并到这一行

### ISSUE THREAD

**Issue by mizhewei** [gnehs/subtitle-translator-electron#36]
我想是不是可以5行或者10行一起发送，
一是创造一个上下文环境，减少串行合并的情况；
二是降低频率，不太容易触发他的免费限制

一行字幕的字符数毕竟是有限的，我想10行应该也不大容易触碰到它的字符上限

**Comment by gnehs** [comment]
目前 GPT-4 的確是這個方法，但是 GPT-3 的話格式會亂掉所以沒辦法傳太多過去。
