### ISSUE TITLE
希望增加自动计时功能

### ISSUE THREAD

**Issue by Idealisten** [gnehs/subtitle-translator-electron#37]
非付费用户一分钟只能发送三次请求，希望增加自动计时功能每分钟翻译三次而不是直接报错停止翻译

**Comment by neohob** [comment]
+1

**Comment by qihuoren** [comment]
支持

**Comment by gnehs** [comment]
Version 1.0.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/tag/1.0.0
