### ISSUE TITLE
Quality of life adds

### ISSUE THREAD

**Issue by DarkSmileee** [gnehs/subtitle-translator-electron#38]
Here are some quality of life adds I and I think others would like to see

- gpt-4-0314 doen't exist it says (bug?)

Real adds 
- Possibility to add multiple files at once 
- When error because server is overloaded or so, wait x time and auto restart translation
- Auto save when finished (can be an option people need to enable) leep the file name as is and add the right language = file1.nl.srt
- Being able to scrull up without jumping down all the time
- ...

**Comment by gnehs** [comment]
You need to join the GPT-4 API waitlist 
https://openai.com/waitlist/gpt-4-api
