### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by wujie1314** [gnehs/subtitle-translator-electron#4]
#### Describe the bug
![image](https://user-images.githubusercontent.com/41436763/224617944-54c8ee2c-9e49-41aa-b17c-deef9e1e3fe9.png)

**Comment by gnehs** [comment]
Please provide more detailed information, such as: system version, Subtitle Translator version, and the steps to reproduce the issue.

**Comment by wujie1314** [comment]
{
  "name": "subtitle-translator-electron",
  "version": "0.2.1",
  "main": "dist-electron/main/index.js",
  "description": "Translate subtitle using ChatGPT",
  "author": "gnehs",
  "license": "MIT",
  "private": true,
  "debug": {
    "env": {
      "VITE_DEV_SERVER_URL": "http://127.0.0.1:7777/"
    }
  },
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build && electron-builder",
    "preview": "vite preview",
    "pree2e": "vite build --mode=test",
    "e2e": "playwright test"
  },
  "devDependencies": {
    "@playwright/test": "^1.31.0",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@vitejs/plugin-react": "^3.1.0",
    "electron": "^24.0.0-beta.1",
    "electron-builder": "^23.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.58.3",
    "typescript": "^4.9.5",
    "vite": "^4.1.4",
    "vite-electron-plugin": "^0.8.2",
    "vite-plugin-electron": "^0.11.1",
    "vite-plugin-electron-renderer": "^0.12.1"
  },
  "engines": {
    "node": "^14.18.0 || >=16.0.0"
  },
  "dependencies": {
    "ass-parser": "^0.2.0",
    "ass-stringify": "^0.1.3",
    "normalize.css": "^8.0.1",
    "openai": "^3.2.1",
    "react-tooltip": "^5.10.0",
    "subtitle": "^4.2.1"
  }
}

**Comment by gnehs** [comment]
Perhaps you can try running `npm run dev`, it works well on my computer.

![image](https://user-images.githubusercontent.com/16719720/224619963-53867da3-85a4-4b8f-8b99-2f0f1bcbc3d8.png)

**Comment by wujie1314** [comment]
![image](https://user-images.githubusercontent.com/41436763/224624465-a0283aa8-eb1d-4a38-b627-209eb3a154a3.png)
npm run dev

**Comment by wujie1314** [comment]
I can use npm run dev
![image](https://user-images.githubusercontent.com/41436763/224867845-8c67308d-82bd-42d9-b099-220629bcf2d4.png)
but use npm run preview
![image](https://user-images.githubusercontent.com/41436763/224868005-52f5b1c5-96c9-42a7-9b97-f98c2b89501e.png)

**Comment by gnehs** [comment]
this project doesn't support `npm run preview`
