### ISSUE TITLE
[Help] How to switch the position of original subtitle and translated subtitle?

### ISSUE THREAD

**Issue by qumino2** [gnehs/subtitle-translator-electron#42]
#### Describe the problem you confuse
Hi, is it possible to switch the position of original subtitle and translated subtitle? The default setting seems that translated subtitle is on top of original subtitle, however, my use case prefer that original subtitle is on top. Thanks!

**Comment by gnehs** [comment]
Version 1.0.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/tag/1.0.0
