### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by dynjo** [gnehs/subtitle-translator-electron#47]
#### Which method you use?

- [X] `gpt-4-0314`
- [ ] `gpt-3.5-turbo`
- [ ] `gpt-3.5-turbo-economy`
#### Provide your subtitle file
[Dungeons.And.Dragons.Honor.Among.Thieves.English-WWW.MY-SUBS.CO.srt.zip](https://github.com/gnehs/subtitle-translator-electron/files/11399155/Dungeons.And.Dragons.Honor.Among.Thieves.English-WWW.MY-SUBS.CO.srt.zip)
#### Target language
Thai
#### Additional notes
None
#### Describe the bug
Gets a few percent in and throws `TypeError: Cannot read properties of undefined (reading 'data')`
#### To Reproduce
Normal use as per instructions

**Comment by gnehs** [comment]
Version 1.0.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/tag/1.0.0
