### ISSUE TITLE
[Bug] SyntaxError: Expected ',' or ']' after array element in JSON at position 144

### ISSUE THREAD

**Issue by dynjo** [gnehs/subtitle-translator-electron#48]
#### Which method you use?

- [X] `gpt-4-0314`
- [ ] `gpt-3.5-turbo`
- [ ] `gpt-3.5-turbo-economy`
#### Provide your subtitle file
[Dungeons.And.Dragons.Honor.Among.Thieves.English-WWW.MY-SUBS.CO (1).srt.zip](https://github.com/gnehs/subtitle-translator-electron/files/11399185/Dungeons.And.Dragons.Honor.Among.Thieves.English-WWW.MY-SUBS.CO.1.srt.zip)
#### Target language
Thai
#### Additional notes
None
#### Describe the bug
Throws a `SyntaxError: Expected ',' or ']' after array element in JSON at position 144`
#### To Reproduce
Normal use

**Comment by gnehs** [comment]
Version 1.0.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/tag/1.0.0
