### ISSUE TITLE
[Bug] Skipped a Line messing up the entire subtitle

### ISSUE THREAD

**Issue by Aeslyy** [gnehs/subtitle-translator-electron#49]
#### Which method you use?
- [ ] `gpt-3.5-turbo`
#### Provide your subtitle file
[https://drive.google.com/file/d/1uyr2in1668awf688ye_46Ul17ZpTb21Q/view?usp=share_link](https://drive.google.com/file/d/1uyr2in1668awf688ye_46Ul17ZpTb21Q/view?usp=share_link)
#### Target language
Brazilian Portuguese

#### Additional notes
Tradução de um donghua.
#### Describe the bug
I will bring the prints to show the problem:

<img src="https://i.imgur.com/t1JfWcl.png" alt="Image 1">
The caption of line 151, was not translated, used the space of line 151 as if it were line 152, skipping and messing up the whole translation.

---
<img src="https://i.imgur.com/0vxdqgg.png" alt="Image 2">
With this problem, another legend was created and repeated with the last one.

---

**Comment by gnehs** [comment]
That's a problem with GPT-3. You can try GPT-4 by joining the GPT-4 API waitlist at https://openai.com/waitlist/gpt-4-api.
