### ISSUE TITLE
[Help] Replace chatgpt by Fastchat

### ISSUE THREAD

**Issue by cjhonlyone** [gnehs/subtitle-translator-electron#50]
FastChat is a local model with with 90% ChatGPT quality. The most important is free to use.
And FastChat has OpenAI-Compatible RESTful APIs & SDK.
So it's helpful to add a option to replace openai to fastchat api.
Thanks!

**Comment by gnehs** [comment]
The functionality to set the OpenAI API host has been added in version 0.6.0. If the FastChat API is compatible with ChatGPT, you will be able to use FastChat through this option.
