### ISSUE TITLE
REQ: auto resume after time-out

### ISSUE THREAD

**Issue by msaborg** [gnehs/subtitle-translator-electron#51]
It happens a lot that during a translating the program halts due to unaivalability of the model:
![image](https://github.com/gnehs/subtitle-translator-electron/assets/127974217/9b7ce594-f9c0-454e-a9b7-35be5ae6c528)

Is it possible to include an option for auto resume?
That is, if this happens, the app will retry in 10 secs?

**Comment by gnehs** [comment]
fixed in version 0.5.1
