### ISSUE TITLE
[Help] 不支持阅览上下文翻译 hmm

### ISSUE THREAD

**Issue by yhuhuhulwkd** [gnehs/subtitle-translator-electron#55]
#### Describe the problem you confuse
如题，不支持阅览上下文翻译 hmm

**Comment by yhuhuhulwkd** [comment]
另外在某些情况下 例如 A 行翻译的是 你好 那么 B 行翻译的也同 A 行 可自行复现

**Comment by gnehs** [comment]
Which method do you use?

**Comment by yhuhuhulwkd** [comment]
> Which method do you use?

GPT3.5

**Comment by chiachunli08** [comment]
我也有遇到這個問題, 偶爾會前後行出現重複文字
