### ISSUE TITLE
经常在提前翻译下一行的内容导致重复。Frequently translating the next line in advance results in repetition

### ISSUE THREAD

**Issue by dadaguai3** [gnehs/subtitle-translator-electron#57]
我尝试不同的音频转字幕得到的文件去尝试

**Comment by dadaguai3** [comment]
I tried translating the files obtained from different audio-to-text conversion attempts into English

**Comment by dadaguai3** [comment]
<img width="646" alt="417db76f576e7ffbdbeec1a0c92c2eb" src="https://github.com/gnehs/subtitle-translator-electron/assets/132725962/c3295be2-2925-45aa-b7c6-11f45507967c">

**Comment by dadaguai3** [comment]
<img width="644" alt="d17a729222cd29271482c522303c5c6" src="https://github.com/gnehs/subtitle-translator-electron/assets/132725962/4b909454-da5c-4458-8e92-59165ce24e24">

**Comment by dadaguai3** [comment]
正常应该是

**Comment by dadaguai3** [comment]
当我在左侧添加（不要提前翻译下一句）整体好多了

**Comment by dadaguai3** [comment]
gpt-3.5-turbo-economy没有这个问题，他很棒，只不过在准确度上和另一个3.5差一些

**Comment by AndersenQin** [comment]
同样的问题，这应该和文章的联想提交有关。很难规避

**Comment by gnehs** [comment]
That is the issue related to ChatGPT; it's hard to fix. You can try GPT-4 for better translation results.
