### ISSUE TITLE
[Bug]无法连接或者接口错误

### ISSUE THREAD

**Issue by kxp9015** [gnehs/subtitle-translator-electron#58]
刚开始只是进度慢，后来直接显示接口错误

**Comment by kxp9015** [comment]
<img width="254" alt="image" src="https://github.com/gnehs/subtitle-translator-electron/assets/62795271/cc9cf67d-2bf5-4f91-a85e-72286e42a5de">

**Comment by kxp9015** [comment]
<img width="595" alt="image" src="https://github.com/gnehs/subtitle-translator-electron/assets/62795271/135a8427-c2dc-45d6-b930-0611a0d329d8">

**Comment by kxp9015** [comment]
作者nb，但是有空看下奥

**Comment by gnehs** [comment]
Is your account linked to a credit card?

**Comment by gnehs** [comment]
> > to
> 
> Yes, I have already linked my credit card. I have also used the software to translate many things before, but it suddenly stopped working today.

 It could be an issue with OpenAI. Please try again later.

**Comment by kxp9015** [comment]
If so, which step should I check or should I wait until tomorrow when it might be better?

> > > to
> > 
> > 
> > Yes, I have already linked my credit card. I have also used the software to translate many things before, but it suddenly stopped working today.是的，我已经关联了我的信用卡。我之前也用过这个软件翻译很多东西，但今天突然就停止工作了。
> 
> It could be an issue with OpenAI. Please try again later.这可能是OpenAI的问题。请稍后再试。

If so, which step should I check or should I wait until tomorrow when it might be better?

**Comment by kxp9015** [comment]
<img width="794" alt="image" src="https://github.com/gnehs/subtitle-translator-electron/assets/62795271/ba030fe1-ec28-45a0-8696-008706561bc1">
