### ISSUE TITLE
默认的3.5 翻译几十行后就会提示 该模型目前因其他请求而过载,您可以重试您的请求

### ISSUE THREAD

**Issue by qihuoren** [gnehs/subtitle-translator-electron#60]
#### Describe the problem you confuse
用的免费额度的3.5api 一份500行的字幕需要大约30分钟以上才能翻译完 中间这个提示会大约提示20次.
有其他解决方案吗 付费版的3.5plus 会好一点吗

**Comment by guavashine** [comment]
我用绑卡的key同样会出现这种提示，两个3.5模型都如此，不确定是不是因为网络原因，不然怎么没什么人来报错~

**Comment by qihuoren** [comment]
我也用了绑卡的也会提示.可能和网络无关吧.我尝试换了多种网络都会提示.

**Comment by gold16** [comment]
今天第一次使用，也是这个情况，我是plus，能否增加自动重试功能

**Comment by gnehs** [comment]
Version 1.0.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/tag/1.0.0
