### ISSUE TITLE
[Bug] Although subscribed to ChatGPT, get message 'gpt-4' does not exist

### ISSUE THREAD

**Issue by nonprogrammodaunpo** [gnehs/subtitle-translator-electron#64]
I subscribed to ChatGPT, so I can now access Model: GPT-4, but I still get this error message in 

The model: 'gpt-4-0314' does
not exist

what am I missing?
thanks so much!

bought you a coffee!!

Marco

#### Which method you use?

- [ ] `gpt-4-0314`
- [ ] `gpt-3.5-turbo`
- [ ] `gpt-3.5-turbo-economy`

**Comment by gnehs** [comment]
To use GPT-4, you need to join the GPT-4 API waitlist.
