### ISSUE TITLE
GPT4 method error

### ISSUE THREAD

**Issue by MrFutureV** [gnehs/subtitle-translator-electron#65]
![QQ截图20230614121053](https://github.com/gnehs/subtitle-translator-electron/assets/46783891/94127950-6a8c-40fb-97b6-5981b00a18ec)

**Comment by gnehs** [comment]
Version 1.0.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/tag/1.0.0
