### ISSUE TITLE
[Help] 希望保留无上下文，单句翻译功能

### ISSUE THREAD

**Issue by neohob** [gnehs/subtitle-translator-electron#71]
1.0.1里发现少了，单句翻译功能，不使用上下文关联翻译，就是之前的经济模式，因为上下文翻译的结果很多时候不能和原字幕那句匹配，反而单句翻译结果比较好

**Comment by cddqssc** [comment]
Totally aggre

**Comment by gnehs** [comment]
Added in 1.3.0.
