### ISSUE TITLE
Additional notes dont always work

### ISSUE THREAD

**Issue by MrFutureV** [gnehs/subtitle-translator-electron#72]
i found that after done processing one subtitle，if i dont restart the software or force reload,my additional notes wont work，i have to force reload to make it work，thats what i noticed，hopefully u can find a way to fix
![20230616214614](https://github.com/gnehs/subtitle-translator-electron/assets/46783891/3f131324-d8e0-4f91-b33d-4d1d71054f11)

**Comment by gnehs** [comment]
Version 1.1.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron-private/releases/latest

**Comment by MrFutureV** [comment]
> Version 1.1.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue. https://github.com/gnehs/subtitle-translator-electron-private/releases/latest

so now from my understanding,"prompts" should be doing some twisted settings to optimal translation,and "note" should be telling the program what's the topic or type of this subtitle would be.i just post my prompt here and plz take a look if you find anything wrong about how it should work :d
![20231016104640](https://github.com/gnehs/subtitle-translator-electron/assets/46783891/5c9b02eb-b907-46d9-9481-a53ae8dfe23f)
