### ISSUE TITLE
期待对免费API使用者翻译长时间视频的优化

### ISSUE THREAD

**Issue by SymbolicRudolf** [gnehs/subtitle-translator-electron#77]
免费API达到使用频率后会直接翻译下行文本，然后便显示无法翻译，当软体把所有文本输入API之后仍然有相当一部分文本未翻译，若想继续翻译必须重复上一步操作，导致在翻译长时间文本的过程中必须多次手动让软体翻译之前未完成的文本；
请问是否可以添加在等待期限结束后再继续翻译文本，而不是直接拿使用频率达到上限的Key继续翻译的选项？

**Comment by fangs233** [comment]
我也遇到这种问题，希望作者能解决

**Comment by gnehs** [comment]
Version 1.1.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron-private/releases/latest
