### ISSUE TITLE
Failed to translate line error

### ISSUE THREAD

**Issue by horzorot** [gnehs/subtitle-translator-electron#78]
Why am I getting this error when I try to translate?
![screenshot](https://github.com/gnehs/subtitle-translator-electron/assets/64330834/faf0323f-840c-4c53-81f7-268f6770765e)

**Comment by piZiAi** [comment]
I have same problem! I want to translate English to Traditional Chinese><

**Comment by macoto1209** [comment]
same here,when translate English to Traditional Chinese,version 1.1.0.

**Comment by Minehors** [comment]
I have it all the time idk what i'm doing wrong

**Comment by gnehs** [comment]
Do you have the API token configured?

**Comment by Minehors** [comment]
> Do you have the API token configured?

i do 
![image](https://github.com/gnehs/subtitle-translator-electron/assets/39132371/430028a6-7e26-42a4-9413-4d9b3909b9c3)

**Comment by Minehors** [comment]
so i should buy premium right to translate ?

**Comment by gnehs** [comment]
> so i should buy premium right to translate ?

Whether having a premium subscription is unrelated to API permissions.

Can you open the latest version (1.3.0) of the subtitle translator, click on 'Start Translation,' and see what it prints?

![image](https://github.com/gnehs/subtitle-translator-electron/assets/16719720/5104a6cd-6ec0-4cbb-a489-c92f4f99e53a)

**Comment by Minehors** [comment]
To be fair its a fresh api key btw 

`5 nov 2023 | Never`

its stateds never in the api keys 
but still get errors

![image](https://github.com/gnehs/subtitle-translator-electron/assets/39132371/4317aa41-82cb-4dec-a456-73327c17595e)

**Comment by gnehs** [comment]
> To be fair its a fresh api key btw
> 
> `5 nov 2023 | Never`
> 
> its stateds never in the api keys but still get errors
> 
> ![image](https://user-images.githubusercontent.com/39132371/282521964-4317aa41-82cb-4dec-a456-73327c17595e.png)

The usage of tokens is currently calculated based on accounts. According to your screenshot, this issue seems unrelated to the subtitle translator.

**Comment by Minehors** [comment]
> > To be fair its a fresh api key btw
> > `5 nov 2023 | Never`
> > its stateds never in the api keys but still get errors
> > ![image](https://user-images.githubusercontent.com/39132371/282521964-4317aa41-82cb-4dec-a456-73327c17595e.png)
> 
> The usage of tokens is currently calculated based on accounts. According to your screenshot, this issue seems unrelated to the subtitle translator.
> 
> You may need to contact OpenAI customer service for more details.

what shoeld i ask them though?
