### ISSUE TITLE
Some subtitles cannot be translated

### ISSUE THREAD

**Issue by pipster439** [gnehs/subtitle-translator-electron#79]
I encounter these errors when translating subtitles,![image](https://github.com/gnehs/subtitle-translator-electron/assets/135446486/df82ecf9-92c8-426b-ab11-cb66e3e628a4) and I'm not sure what the problem is, as I'm already using 10 APIs simultaneously.

**Comment by willsherlock** [comment]
我也同样遇到了该问题，有解决的办法吗

**Comment by gnehs** [comment]
Version 1.3.0 has addressed some translation issues. Please give it a try. If the problem persists, please open this issue again.
