### ISSUE TITLE
We need a version that supports browser login not via API

### ISSUE THREAD

**Issue by FurkanGozukara** [gnehs/subtitle-translator-electron#8]
I got chatGPT plus

it can translate entire subtitle but you have to split it into like 1 minute frames and type again and again

which takes huge time

can you modify it so that we can use chat GPT plus subscription not API?

**Comment by gnehs** [comment]
I know the speed is slow, but after OpenAI releases the GPT-4 API, we should be able to integrate it as soon as possible. At that time, it may be possible to send the entire subtitle file in one request.

**Comment by FurkanGozukara** [comment]
> I know the speed is slow, but after OpenAI releases the GPT-4 API, we should be able to integrate it as soon as possible. At that time, it may be possible to send the entire subtitle file in one request.

Speed not the issue. Currently api costs money. But when you become chat gpt plus subscriber it is free for unlimited token. Could you make it use chat gpt plus subscription? Probably via browser integration?

**Comment by gnehs** [comment]
There are currently no plans for that.
