### ISSUE TITLE
运行源码报错Failed to translate line: NaN Error: connect ETIMEDOUT 69.171.234.48:443 Retrying translation for line: NaN，怎么解决？

### ISSUE THREAD

**Issue by HanniYang721** [gnehs/subtitle-translator-electron#81]

**Comment by HanniYang721** [comment]
网络能正常登录网页版ChatGPT，什么原因导致API访问不行呢？

**Comment by gnehs** [comment]
Version 1.1.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/latest
