### ISSUE TITLE
stopped many times and cannot complete

### ISSUE THREAD

**Issue by jackcore21** [gnehs/subtitle-translator-electron#82]
I'm sorry your application could not fully translate your electronic version. It stopped at 55%, 68%, and 73% despite my repeated attempts. I added the 4 API key, but it didn't help. I had to spend money on this service, but it seemed it was all for nothing. Please fix your application.

**Comment by gnehs** [comment]
Version 1.1.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/latest
