### ISSUE TITLE
Failed to translate for all lines

### ISSUE THREAD

**Issue by natayik** [gnehs/subtitle-translator-electron#83]
Not sure if it's a bug or I didn't set it up right. After adding the API key and upload my file, it wouldn't translate. Gets the failed to translate message for all lines. I'm on Mac.
<img width="925" alt="Screenshot 2023-08-19 at 4 07 22 PM" src="https://github.com/gnehs/subtitle-translator-electron/assets/142698202/f9d2a85d-2e40-4cfe-a588-1f1d050e11c2">

**Comment by SMooxx** [comment]
同样卡死，一个有1500行的英文字幕，时长46分钟，卡死两次了 

![image](https://github.com/gnehs/subtitle-translator-electron/assets/9960618/883920bf-35ba-471b-9453-d2abd15c3b8f)

**Comment by zakghibli** [comment]
Failed to translate for all lines same problem

**Comment by infini667** [comment]
error message simulator...

**Comment by gnehs** [comment]
Version 1.1.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron-private/releases/latest
