### ISSUE TITLE
[Help] 無法翻譯該行字幕

### ISSUE THREAD

**Issue by jeff4669leo** [gnehs/subtitle-translator-electron#85]
無法翻譯該行字幕 Ｔ^Ｔ 請求協助

<img width="412" alt="截圖 2023-10-10 00 39 09" src="https://github.com/gnehs/subtitle-translator-electron/assets/147428865/eddffccd-095b-48c9-8435-d3699d2692a7">

**Comment by gnehs** [comment]
Version 1.1.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron-private/releases/latest

**Comment by jeff4669leo** [comment]
已經更新到最新版，但還是一樣呈現同樣的狀況：無法翻譯該行字幕
