### ISSUE TITLE
[Help] Users can choose models.

### ISSUE THREAD

**Issue by missuo** [gnehs/subtitle-translator-electron#86]
#### Describe the problem you confuse
Hope to have an additional option where users can choose the model they want, such as `GPT-3.5-Turbo` or `GPT-4`.

**Comment by sqy941013** [comment]
especially openai released gpt4-1106

**Comment by tvone** [comment]
I have updated a version where users can choose a custom model
https://github.com/tvone/subtitle-translator-electron/releases/tag/subtitle

**Comment by gnehs** [comment]
<img width="801" alt="image" src="https://github.com/gnehs/subtitle-translator-electron/assets/16719720/9460970d-fc7a-4a55-8b20-a5b793c2b4b1">
Version 1.4.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/latest
