### ISSUE TITLE
[Help] unable to run subtitle-translator-electron in Windows 7 64bit

### ISSUE THREAD

**Issue by wahkee** [gnehs/subtitle-translator-electron#93]
#### Describe the problem you confuse
I tried to install  subtitle-translator_1.1.0.exe in Windows 7 64bit, however, it show the error messages as attached.
![2023_005](https://github.com/gnehs/subtitle-translator-electron/assets/150553689/53bc701e-a51b-40a2-b210-341f3a7a3f9d)
Please help and assist, thank you.

**Comment by gnehs** [comment]
Subtitle Translator Electron does not support Windows 7. Please use Windows 10 or above.

ref:
https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
