### ISSUE TITLE
[Help] Able to choose fine-tune model

### ISSUE THREAD

**Issue by pantasa** [gnehs/subtitle-translator-electron#95]
Dear @gnehs 

Love your product. Can you create option to choose fine-tune models? The default models doesn't cut it. I have my own fine-tune chatgpt 3.5 that I would like to use. Thank you very much. I dont have much but sent you a coffee.

**Comment by tvone** [comment]
I have updated a version where users can choose a custom model
https://github.com/tvone/subtitle-translator-electron/releases/tag/subtitle

**Comment by gnehs** [comment]
<img width="801" alt="image" src="https://github.com/gnehs/subtitle-translator-electron/assets/16719720/9460970d-fc7a-4a55-8b20-a5b793c2b4b1">
Version 1.4.0 has been released. Please give it a try, and if you encounter any issues, feel free to raise an issue.
https://github.com/gnehs/subtitle-translator-electron/releases/latest
